---
ahoyapi: v2

commands:

  lint:
    name: Lint Scaffold project.
    cmd: |
      ahoy lint-scripts
      ahoy lint-dockerfiles
      ahoy lint-docs

  lint-scripts:
    cmd: ./tests/lint.scripts.sh

  lint-dockerfiles:
    cmd: ./tests/lint.dockerfiles.sh

  lint-docs:
    cmd: |
      npm --prefix=./docs ci
      npm --prefix=./docs run test

  test:
    name: Test Scaffold project.
    cmd: |
      ahoy test-common
      ahoy test-docs

  test-common:
    cmd: ./tests/test.common.sh

  test-deployment:
    cmd: ./tests/test.deployment.sh

  test-workflow:
    cmd: ./tests/test.workflow.sh

  test-docs:
    cmd: ahoy docs build && ahoy docs test

  # If there are changes to the fixtures - this command will re-run twice reporting error the first time.
  update-fixtures:
    cmd: |
      cd ../ \
      && UPDATE_FIXTURES=1 bats ./tests/bats/docker-compose.bats \
      || UPDATE_FIXTURES=1 bats ./tests/bats/docker-compose.bats

  update-docs:
    usage: Update the documentation.
    cmd: |
      composer --working-dir=./docs/.utils install
      npm --prefix=./docs run update-variables

entrypoint:
  - bash
  - "-c"
  - "-e"
  - bash -e -c "$0" "$@"
  - '{{cmd}}'
  - '{{name}}'
